-- Migration: RBAC System für feingranulare Berechtigungen
-- Erstellt Tabellen für Rollen, Berechtigungen und Rollenzuweisungen

-- Tabelle für Rollen
create table "public"."roles" (
    "id" bigint generated by default as identity not null,
    "name" text not null unique,
    "description" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);

alter table "public"."roles" enable row level security;
CREATE UNIQUE INDEX roles_pkey ON public.roles USING btree (id);
alter table "public"."roles" add constraint "roles_pkey" PRIMARY KEY using index "roles_pkey";

-- Tabelle für Berechtigungen pro Rolle
create table "public"."role_permissions" (
    "id" bigint generated by default as identity not null,
    "role_id" bigint not null,
    "resource" text not null, -- 'contacts', 'companies', 'deals', 'tasks', 'notes'
    "action" text not null, -- 'list', 'show', 'create', 'edit', 'delete'
    "scope" text not null default 'all', -- 'all', 'own', 'team', 'none'
    "created_at" timestamp with time zone not null default now()
);

alter table "public"."role_permissions" enable row level security;
CREATE UNIQUE INDEX role_permissions_pkey ON public.role_permissions USING btree (id);
CREATE UNIQUE INDEX role_permissions_unique ON public.role_permissions USING btree (role_id, resource, action);
alter table "public"."role_permissions" add constraint "role_permissions_pkey" PRIMARY KEY using index "role_permissions_pkey";
alter table "public"."role_permissions" add constraint "role_permissions_role_id_fkey" FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE;

-- Rollenzuweisung zu Benutzern (sales)
alter table "public"."sales" add column "role_id" bigint;
alter table "public"."sales" add constraint "sales_role_id_fkey" FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE SET NULL;

-- Team-Tabelle für Team-basierte Berechtigungen
create table "public"."teams" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "description" text,
    "created_at" timestamp with time zone not null default now()
);

alter table "public"."teams" enable row level security;
CREATE UNIQUE INDEX teams_pkey ON public.teams USING btree (id);
alter table "public"."teams" add constraint "teams_pkey" PRIMARY KEY using index "teams_pkey";

-- Team-Mitgliedschaft
create table "public"."team_members" (
    "id" bigint generated by default as identity not null,
    "team_id" bigint not null,
    "sales_id" bigint not null,
    "is_leader" boolean default false,
    "created_at" timestamp with time zone not null default now()
);

alter table "public"."team_members" enable row level security;
CREATE UNIQUE INDEX team_members_pkey ON public.team_members USING btree (id);
CREATE UNIQUE INDEX team_members_unique ON public.team_members USING btree (team_id, sales_id);
alter table "public"."team_members" add constraint "team_members_pkey" PRIMARY KEY using index "team_members_pkey";
alter table "public"."team_members" add constraint "team_members_team_id_fkey" FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
alter table "public"."team_members" add constraint "team_members_sales_id_fkey" FOREIGN KEY (sales_id) REFERENCES sales(id) ON DELETE CASCADE;

-- Hilfsfunktion: Aktuellen Sales-Benutzer ermitteln
create or replace function public.get_current_sales_id()
returns bigint
language sql
security definer
stable
as $$
  select id from public.sales where user_id = auth.uid()
$$;

-- Hilfsfunktion: Prüfen ob aktueller Benutzer Admin ist
create or replace function public.is_admin()
returns boolean
language sql
security definer
stable
as $$
  select coalesce(
    (select administrator from public.sales where user_id = auth.uid()),
    false
  )
$$;

-- Hilfsfunktion: Berechtigung für Ressource und Aktion prüfen
create or replace function public.check_permission(
  p_resource text,
  p_action text
)
returns text -- Gibt den Scope zurück: 'all', 'own', 'team', 'none'
language sql
security definer
stable
as $$
  select coalesce(
    (
      select rp.scope
      from public.sales s
      join public.role_permissions rp on rp.role_id = s.role_id
      where s.user_id = auth.uid()
        and rp.resource = p_resource
        and rp.action = p_action
    ),
    case 
      when public.is_admin() then 'all'
      else 'none'
    end
  )
$$;

-- Hilfsfunktion: Team-Mitglieder IDs ermitteln
create or replace function public.get_team_member_ids()
returns bigint[]
language sql
security definer
stable
as $$
  select array_agg(distinct tm2.sales_id)
  from public.team_members tm1
  join public.team_members tm2 on tm1.team_id = tm2.team_id
  where tm1.sales_id = public.get_current_sales_id()
$$;

-- Hilfsfunktion: Prüfen ob Benutzer Zugriff auf einen Datensatz hat
create or replace function public.has_record_access(
  p_resource text,
  p_action text,
  p_sales_id bigint
)
returns boolean
language sql
security definer
stable
as $$
  select case public.check_permission(p_resource, p_action)
    when 'all' then true
    when 'own' then p_sales_id = public.get_current_sales_id()
    when 'team' then p_sales_id = any(public.get_team_member_ids())
    else false
  end
$$;

-- Standard-Rollen erstellen
insert into public.roles (name, description) values
  ('Administrator', 'Vollzugriff auf alle Ressourcen'),
  ('Vertriebsleiter', 'Zugriff auf Team-Daten und eigene Daten'),
  ('Vertriebsmitarbeiter', 'Nur Zugriff auf eigene Daten');

-- Standard-Berechtigungen für Administrator
insert into public.role_permissions (role_id, resource, action, scope)
select 
  (select id from public.roles where name = 'Administrator'),
  resource,
  action,
  'all'
from (
  values 
    ('contacts', 'list'), ('contacts', 'show'), ('contacts', 'create'), ('contacts', 'edit'), ('contacts', 'delete'),
    ('companies', 'list'), ('companies', 'show'), ('companies', 'create'), ('companies', 'edit'), ('companies', 'delete'),
    ('deals', 'list'), ('deals', 'show'), ('deals', 'create'), ('deals', 'edit'), ('deals', 'delete'),
    ('tasks', 'list'), ('tasks', 'show'), ('tasks', 'create'), ('tasks', 'edit'), ('tasks', 'delete'),
    ('contact_notes', 'list'), ('contact_notes', 'show'), ('contact_notes', 'create'), ('contact_notes', 'edit'), ('contact_notes', 'delete'),
    ('deal_notes', 'list'), ('deal_notes', 'show'), ('deal_notes', 'create'), ('deal_notes', 'edit'), ('deal_notes', 'delete'),
    ('sales', 'list'), ('sales', 'show'), ('sales', 'create'), ('sales', 'edit'), ('sales', 'delete'),
    ('roles', 'list'), ('roles', 'show'), ('roles', 'create'), ('roles', 'edit'), ('roles', 'delete'),
    ('teams', 'list'), ('teams', 'show'), ('teams', 'create'), ('teams', 'edit'), ('teams', 'delete')
) as t(resource, action);

-- Standard-Berechtigungen für Vertriebsleiter (Team-Scope)
insert into public.role_permissions (role_id, resource, action, scope)
select 
  (select id from public.roles where name = 'Vertriebsleiter'),
  resource,
  action,
  'team'
from (
  values 
    ('contacts', 'list'), ('contacts', 'show'), ('contacts', 'create'), ('contacts', 'edit'), ('contacts', 'delete'),
    ('companies', 'list'), ('companies', 'show'), ('companies', 'create'), ('companies', 'edit'), ('companies', 'delete'),
    ('deals', 'list'), ('deals', 'show'), ('deals', 'create'), ('deals', 'edit'), ('deals', 'delete'),
    ('tasks', 'list'), ('tasks', 'show'), ('tasks', 'create'), ('tasks', 'edit'), ('tasks', 'delete'),
    ('contact_notes', 'list'), ('contact_notes', 'show'), ('contact_notes', 'create'), ('contact_notes', 'edit'), ('contact_notes', 'delete'),
    ('deal_notes', 'list'), ('deal_notes', 'show'), ('deal_notes', 'create'), ('deal_notes', 'edit'), ('deal_notes', 'delete')
) as t(resource, action);

-- Vertriebsleiter darf Sales und Teams sehen
insert into public.role_permissions (role_id, resource, action, scope)
select 
  (select id from public.roles where name = 'Vertriebsleiter'),
  resource,
  action,
  'team'
from (
  values 
    ('sales', 'list'), ('sales', 'show'),
    ('teams', 'list'), ('teams', 'show')
) as t(resource, action);

-- Standard-Berechtigungen für Vertriebsmitarbeiter (Own-Scope)
insert into public.role_permissions (role_id, resource, action, scope)
select 
  (select id from public.roles where name = 'Vertriebsmitarbeiter'),
  resource,
  action,
  'own'
from (
  values 
    ('contacts', 'list'), ('contacts', 'show'), ('contacts', 'create'), ('contacts', 'edit'),
    ('companies', 'list'), ('companies', 'show'),
    ('deals', 'list'), ('deals', 'show'), ('deals', 'create'), ('deals', 'edit'),
    ('tasks', 'list'), ('tasks', 'show'), ('tasks', 'create'), ('tasks', 'edit'), ('tasks', 'delete'),
    ('contact_notes', 'list'), ('contact_notes', 'show'), ('contact_notes', 'create'), ('contact_notes', 'edit'),
    ('deal_notes', 'list'), ('deal_notes', 'show'), ('deal_notes', 'create'), ('deal_notes', 'edit')
) as t(resource, action);

-- Grants für neue Tabellen
grant select, insert, update, delete on table "public"."roles" to "authenticated";
grant select, insert, update, delete on table "public"."role_permissions" to "authenticated";
grant select, insert, update, delete on table "public"."teams" to "authenticated";
grant select, insert, update, delete on table "public"."team_members" to "authenticated";

grant all on table "public"."roles" to "service_role";
grant all on table "public"."role_permissions" to "service_role";
grant all on table "public"."teams" to "service_role";
grant all on table "public"."team_members" to "service_role";

-- RLS Policies für roles (nur Admins)
create policy "Roles read for authenticated"
on "public"."roles"
for select
to authenticated
using (true);

create policy "Roles write for admins"
on "public"."roles"
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- RLS Policies für role_permissions (nur Admins)
create policy "Role permissions read for authenticated"
on "public"."role_permissions"
for select
to authenticated
using (true);

create policy "Role permissions write for admins"
on "public"."role_permissions"
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- RLS Policies für teams
create policy "Teams read for authenticated"
on "public"."teams"
for select
to authenticated
using (true);

create policy "Teams write for admins"
on "public"."teams"
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- RLS Policies für team_members
create policy "Team members read for authenticated"
on "public"."team_members"
for select
to authenticated
using (true);

create policy "Team members write for admins"
on "public"."team_members"
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Aktualisierte RLS Policies für contacts mit RBAC
drop policy if exists "Enable read access for authenticated users" on "public"."contacts";
create policy "Contacts read with RBAC"
on "public"."contacts"
for select
to authenticated
using (
  public.is_admin() 
  or public.has_record_access('contacts', 'list', sales_id)
);

drop policy if exists "Enable insert for authenticated users only" on "public"."contacts";
create policy "Contacts insert with RBAC"
on "public"."contacts"
for insert
to authenticated
with check (
  public.is_admin()
  or public.check_permission('contacts', 'create') in ('all', 'own', 'team')
);

drop policy if exists "Enable update for authenticated users only" on "public"."contacts";
create policy "Contacts update with RBAC"
on "public"."contacts"
for update
to authenticated
using (
  public.is_admin()
  or public.has_record_access('contacts', 'edit', sales_id)
)
with check (
  public.is_admin()
  or public.has_record_access('contacts', 'edit', sales_id)
);

drop policy if exists "Contact Delete Policy" on "public"."contacts";
create policy "Contacts delete with RBAC"
on "public"."contacts"
for delete
to authenticated
using (
  public.is_admin()
  or public.has_record_access('contacts', 'delete', sales_id)
);

-- Aktualisierte RLS Policies für companies mit RBAC
drop policy if exists "Enable read access for authenticated users" on "public"."companies";
create policy "Companies read with RBAC"
on "public"."companies"
for select
to authenticated
using (
  public.is_admin() 
  or public.has_record_access('companies', 'list', sales_id)
);

drop policy if exists "Enable insert for authenticated users only" on "public"."companies";
create policy "Companies insert with RBAC"
on "public"."companies"
for insert
to authenticated
with check (
  public.is_admin()
  or public.check_permission('companies', 'create') in ('all', 'own', 'team')
);

drop policy if exists "Enable update for authenticated users only" on "public"."companies";
create policy "Companies update with RBAC"
on "public"."companies"
for update
to authenticated
using (
  public.is_admin()
  or public.has_record_access('companies', 'edit', sales_id)
)
with check (
  public.is_admin()
  or public.has_record_access('companies', 'edit', sales_id)
);

drop policy if exists "Company Delete Policy" on "public"."companies";
create policy "Companies delete with RBAC"
on "public"."companies"
for delete
to authenticated
using (
  public.is_admin()
  or public.has_record_access('companies', 'delete', sales_id)
);

-- Aktualisierte RLS Policies für deals mit RBAC
drop policy if exists "Enable read access for authenticated users" on "public"."deals";
create policy "Deals read with RBAC"
on "public"."deals"
for select
to authenticated
using (
  public.is_admin() 
  or public.has_record_access('deals', 'list', sales_id)
);

drop policy if exists "Enable insert for authenticated users only" on "public"."deals";
create policy "Deals insert with RBAC"
on "public"."deals"
for insert
to authenticated
with check (
  public.is_admin()
  or public.check_permission('deals', 'create') in ('all', 'own', 'team')
);

drop policy if exists "Enable update for authenticated users only" on "public"."deals";
create policy "Deals update with RBAC"
on "public"."deals"
for update
to authenticated
using (
  public.is_admin()
  or public.has_record_access('deals', 'edit', sales_id)
)
with check (
  public.is_admin()
  or public.has_record_access('deals', 'edit', sales_id)
);

drop policy if exists "Deals Delete Policy" on "public"."deals";
create policy "Deals delete with RBAC"
on "public"."deals"
for delete
to authenticated
using (
  public.is_admin()
  or public.has_record_access('deals', 'delete', sales_id)
);

-- View für Berechtigungsübersicht aktualisieren
create or replace view "public"."user_permissions"
with (security_invoker=on)
as
select 
  s.id as sales_id,
  s.first_name,
  s.last_name,
  s.administrator,
  r.name as role_name,
  rp.resource,
  rp.action,
  rp.scope
from public.sales s
left join public.roles r on s.role_id = r.id
left join public.role_permissions rp on r.id = rp.role_id
where s.user_id = auth.uid();
