-- Migration: ABAC (Attribute-Based Access Control) Erweiterung
-- Ermöglicht Zugriffsbeschränkungen basierend auf Benutzer-/Rollenattributen
-- =====================================================
-- BENUTZERATTRIBUTE
-- =====================================================

-- Tabelle für Benutzerattribute (z.B. Region, Abteilung, Kostenstelle)
CREATE TABLE IF NOT EXISTS "public"."user_attributes" (
    "id" bigint generated by default as identity not null,
    "sales_id" bigint not null,
    "attribute_name" text not null,
    "attribute_value" text not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);

ALTER TABLE "public"."user_attributes" ENABLE ROW LEVEL SECURITY;

CREATE UNIQUE INDEX IF NOT EXISTS user_attributes_pkey ON public.user_attributes USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS user_attributes_unique ON public.user_attributes USING btree (sales_id, attribute_name);
CREATE INDEX IF NOT EXISTS user_attributes_name_value ON public.user_attributes USING btree (attribute_name, attribute_value);

ALTER TABLE "public"."user_attributes" ADD CONSTRAINT "user_attributes_pkey" PRIMARY KEY using index "user_attributes_pkey";
ALTER TABLE "public"."user_attributes" ADD CONSTRAINT "user_attributes_sales_id_fkey" FOREIGN KEY (sales_id) REFERENCES sales(id) ON DELETE CASCADE;

-- =====================================================
-- ROLLENATTRIBUTE (Standard-Attribute für eine Rolle)
-- =====================================================

CREATE TABLE IF NOT EXISTS "public"."role_attributes" (
    "id" bigint generated by default as identity not null,
    "role_id" bigint not null,
    "attribute_name" text not null,
    "attribute_value" text not null,
    "created_at" timestamp with time zone not null default now()
);

ALTER TABLE "public"."role_attributes" ENABLE ROW LEVEL SECURITY;

CREATE UNIQUE INDEX IF NOT EXISTS role_attributes_pkey ON public.role_attributes USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS role_attributes_unique ON public.role_attributes USING btree (role_id, attribute_name, attribute_value);

ALTER TABLE "public"."role_attributes" ADD CONSTRAINT "role_attributes_pkey" PRIMARY KEY using index "role_attributes_pkey";
ALTER TABLE "public"."role_attributes" ADD CONSTRAINT "role_attributes_role_id_fkey" FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE;

-- =====================================================
-- ATTRIBUTBEDINGUNGEN FÜR BERECHTIGUNGEN
-- =====================================================

-- Tabelle für Attributbedingungen auf Berechtigungen
-- Beispiel: Berechtigung "deals.list" nur wenn deal.region = user.region
CREATE TABLE IF NOT EXISTS "public"."permission_conditions" (
    "id" bigint generated by default as identity not null,
    "role_permission_id" bigint not null,
    "condition_type" text not null, -- 'attribute_match', 'field_value', 'custom_expression'
    "target_field" text not null, -- Feld im Datensatz (z.B. 'region', 'status', 'category')
    "operator" text not null default '=', -- '=', '!=', 'IN', 'NOT IN', '>', '<', '>=', '<=', 'LIKE', 'IS NULL', 'IS NOT NULL'
    "source_type" text not null, -- 'user_attribute', 'role_attribute', 'static_value', 'current_user'
    "source_attribute" text, -- Name des Attributs oder statischer Wert
    "static_values" jsonb, -- Für statische Werte oder IN-Listen
    "logic_operator" text default 'AND', -- 'AND', 'OR' für Verknüpfung mit anderen Bedingungen
    "is_active" boolean not null default true,
    "created_at" timestamp with time zone not null default now()
);

ALTER TABLE "public"."permission_conditions" ENABLE ROW LEVEL SECURITY;

CREATE UNIQUE INDEX IF NOT EXISTS permission_conditions_pkey ON public.permission_conditions USING btree (id);
CREATE INDEX IF NOT EXISTS permission_conditions_role_perm ON public.permission_conditions USING btree (role_permission_id);

ALTER TABLE "public"."permission_conditions" ADD CONSTRAINT "permission_conditions_pkey" PRIMARY KEY using index "permission_conditions_pkey";
ALTER TABLE "public"."permission_conditions" ADD CONSTRAINT "permission_conditions_role_permission_id_fkey" 
    FOREIGN KEY (role_permission_id) REFERENCES role_permissions(id) ON DELETE CASCADE;

-- =====================================================
-- VORDEFINIERTE ATTRIBUTTYPEN
-- =====================================================

CREATE TABLE IF NOT EXISTS "public"."attribute_definitions" (
    "id" bigint generated by default as identity not null,
    "name" text not null unique,
    "label" text not null,
    "description" text,
    "data_type" text not null default 'text', -- 'text', 'number', 'boolean', 'date', 'select'
    "allowed_values" jsonb, -- Für select: [{value: 'x', label: 'X'}]
    "is_system" boolean not null default false, -- System-Attribute können nicht gelöscht werden
    "applies_to" text[] default ARRAY['user', 'role'], -- Wo kann das Attribut verwendet werden
    "created_at" timestamp with time zone not null default now()
);

ALTER TABLE "public"."attribute_definitions" ENABLE ROW LEVEL SECURITY;

CREATE UNIQUE INDEX IF NOT EXISTS attribute_definitions_pkey ON public.attribute_definitions USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS attribute_definitions_name ON public.attribute_definitions USING btree (name);

ALTER TABLE "public"."attribute_definitions" ADD CONSTRAINT "attribute_definitions_pkey" PRIMARY KEY using index "attribute_definitions_pkey";

-- =====================================================
-- HILFSFUNKTIONEN FÜR ABAC
-- =====================================================

-- Benutzerattribut abrufen
CREATE OR REPLACE FUNCTION public.get_user_attribute(p_attribute_name text)
RETURNS text
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
    SELECT attribute_value 
    FROM public.user_attributes 
    WHERE sales_id = public.get_current_sales_id() 
      AND attribute_name = p_attribute_name
    LIMIT 1
$$;

-- Alle Benutzerattribute abrufen
CREATE OR REPLACE FUNCTION public.get_user_attributes()
RETURNS jsonb
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
    SELECT COALESCE(
        jsonb_object_agg(attribute_name, attribute_value),
        '{}'::jsonb
    )
    FROM public.user_attributes 
    WHERE sales_id = public.get_current_sales_id()
$$;

-- Rollenattribut abrufen (aus der Rolle des aktuellen Benutzers)
CREATE OR REPLACE FUNCTION public.get_role_attribute(p_attribute_name text)
RETURNS text[]
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
    SELECT COALESCE(
        array_agg(ra.attribute_value),
        ARRAY[]::text[]
    )
    FROM public.sales s
    JOIN public.role_attributes ra ON ra.role_id = s.role_id
    WHERE s.user_id = auth.uid()
      AND ra.attribute_name = p_attribute_name
$$;

-- Prüfen ob Benutzer ein bestimmtes Attribut mit Wert hat
CREATE OR REPLACE FUNCTION public.has_user_attribute(p_attribute_name text, p_attribute_value text)
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
    SELECT EXISTS (
        SELECT 1 
        FROM public.user_attributes 
        WHERE sales_id = public.get_current_sales_id() 
          AND attribute_name = p_attribute_name
          AND attribute_value = p_attribute_value
    )
$$;

-- ABAC-Bedingung für einen Datensatz prüfen
CREATE OR REPLACE FUNCTION public.check_abac_condition(
    p_role_permission_id bigint,
    p_record jsonb
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
AS $$
DECLARE
    v_condition RECORD;
    v_result boolean := true;
    v_condition_result boolean;
    v_source_value text;
    v_target_value text;
    v_has_and_conditions boolean := false;
    v_has_or_conditions boolean := false;
    v_and_result boolean := true;
    v_or_result boolean := false;
BEGIN
    -- Keine Bedingungen = Zugriff erlaubt
    IF NOT EXISTS (
        SELECT 1 FROM public.permission_conditions 
        WHERE role_permission_id = p_role_permission_id AND is_active = true
    ) THEN
        RETURN true;
    END IF;

    -- Durch alle aktiven Bedingungen iterieren
    FOR v_condition IN 
        SELECT * FROM public.permission_conditions 
        WHERE role_permission_id = p_role_permission_id 
          AND is_active = true
        ORDER BY logic_operator DESC -- AND zuerst, dann OR
    LOOP
        -- Zielwert aus dem Datensatz extrahieren
        v_target_value := p_record ->> v_condition.target_field;
        
        -- Quellwert ermitteln basierend auf source_type
        CASE v_condition.source_type
            WHEN 'user_attribute' THEN
                v_source_value := public.get_user_attribute(v_condition.source_attribute);
            WHEN 'role_attribute' THEN
                -- Bei Rollenattributen: Prüfen ob Zielwert in den Rollenattributen enthalten ist
                v_source_value := (
                    SELECT string_agg(val, ',') 
                    FROM unnest(public.get_role_attribute(v_condition.source_attribute)) AS val
                );
            WHEN 'static_value' THEN
                v_source_value := v_condition.source_attribute;
            WHEN 'current_user' THEN
                v_source_value := public.get_current_sales_id()::text;
            ELSE
                v_source_value := v_condition.source_attribute;
        END CASE;

        -- Operator anwenden
        CASE v_condition.operator
            WHEN '=' THEN
                v_condition_result := (v_target_value = v_source_value);
            WHEN '!=' THEN
                v_condition_result := (v_target_value != v_source_value);
            WHEN '>' THEN
                v_condition_result := (v_target_value::numeric > v_source_value::numeric);
            WHEN '<' THEN
                v_condition_result := (v_target_value::numeric < v_source_value::numeric);
            WHEN '>=' THEN
                v_condition_result := (v_target_value::numeric >= v_source_value::numeric);
            WHEN '<=' THEN
                v_condition_result := (v_target_value::numeric <= v_source_value::numeric);
            WHEN 'LIKE' THEN
                v_condition_result := (v_target_value LIKE v_source_value);
            WHEN 'ILIKE' THEN
                v_condition_result := (v_target_value ILIKE v_source_value);
            WHEN 'IN' THEN
                v_condition_result := (v_target_value = ANY(
                    SELECT jsonb_array_elements_text(v_condition.static_values)
                ));
            WHEN 'NOT IN' THEN
                v_condition_result := NOT (v_target_value = ANY(
                    SELECT jsonb_array_elements_text(v_condition.static_values)
                ));
            WHEN 'IS NULL' THEN
                v_condition_result := (v_target_value IS NULL);
            WHEN 'IS NOT NULL' THEN
                v_condition_result := (v_target_value IS NOT NULL);
            WHEN 'CONTAINS' THEN
                -- Für Rollenattribute: Prüfen ob Zielwert in der Liste enthalten ist
                v_condition_result := (v_target_value = ANY(string_to_array(v_source_value, ',')));
            ELSE
                v_condition_result := true;
        END CASE;

        -- Logik-Operator anwenden
        IF v_condition.logic_operator = 'AND' THEN
            v_has_and_conditions := true;
            v_and_result := v_and_result AND COALESCE(v_condition_result, false);
        ELSE -- OR
            v_has_or_conditions := true;
            v_or_result := v_or_result OR COALESCE(v_condition_result, false);
        END IF;
    END LOOP;

    -- Ergebnis kombinieren
    IF v_has_and_conditions AND v_has_or_conditions THEN
        v_result := v_and_result OR v_or_result;
    ELSIF v_has_and_conditions THEN
        v_result := v_and_result;
    ELSIF v_has_or_conditions THEN
        v_result := v_or_result;
    END IF;

    RETURN v_result;
END;
$$;

-- Erweiterte Zugriffsprüfung mit ABAC
CREATE OR REPLACE FUNCTION public.has_record_access_abac(
    p_resource text,
    p_action text,
    p_sales_id bigint,
    p_record jsonb DEFAULT NULL
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
AS $$
DECLARE
    v_permission_id bigint;
    v_scope text;
    v_basic_access boolean;
BEGIN
    -- Admin hat immer Zugriff
    IF public.is_admin() THEN
        RETURN true;
    END IF;

    -- Basis RBAC-Zugriff prüfen
    v_basic_access := public.has_record_access(p_resource, p_action, p_sales_id);
    
    IF NOT v_basic_access THEN
        RETURN false;
    END IF;

    -- Wenn kein Record übergeben wurde, nur RBAC prüfen
    IF p_record IS NULL THEN
        RETURN v_basic_access;
    END IF;

    -- Permission ID ermitteln für ABAC-Bedingungen
    SELECT rp.id INTO v_permission_id
    FROM public.sales s
    JOIN public.role_permissions rp ON rp.role_id = s.role_id
    WHERE s.user_id = auth.uid()
      AND rp.resource = p_resource
      AND rp.action = p_action;

    -- Keine Permission gefunden = Zugriff basierend auf RBAC
    IF v_permission_id IS NULL THEN
        RETURN v_basic_access;
    END IF;

    -- ABAC-Bedingungen prüfen
    RETURN public.check_abac_condition(v_permission_id, p_record);
END;
$$;

-- =====================================================
-- STANDARD-ATTRIBUTDEFINITIONEN
-- =====================================================

INSERT INTO public.attribute_definitions (name, label, description, data_type, allowed_values, is_system, applies_to)
VALUES
    ('region', 'Region', 'Geografische Region des Benutzers', 'select', 
     '[{"value": "DACH", "label": "DACH (Deutschland, Österreich, Schweiz)"}, {"value": "EMEA", "label": "EMEA"}, {"value": "APAC", "label": "Asien-Pazifik"}, {"value": "AMERICAS", "label": "Amerika"}]'::jsonb,
     true, ARRAY['user', 'role']),
    ('department', 'Abteilung', 'Abteilung des Benutzers', 'select',
     '[{"value": "sales", "label": "Vertrieb"}, {"value": "marketing", "label": "Marketing"}, {"value": "support", "label": "Support"}, {"value": "management", "label": "Management"}]'::jsonb,
     true, ARRAY['user', 'role']),
    ('cost_center', 'Kostenstelle', 'Kostenstelle für Budgetierung', 'text', NULL, false, ARRAY['user']),
    ('max_deal_value', 'Max. Deal-Wert', 'Maximaler Deal-Wert den der Benutzer bearbeiten darf', 'number', NULL, false, ARRAY['user', 'role']),
    ('allowed_stages', 'Erlaubte Stages', 'Deal-Stages die der Benutzer bearbeiten darf', 'select',
     '[{"value": "opportunity", "label": "Opportunity"}, {"value": "proposal", "label": "Angebot"}, {"value": "negotiation", "label": "Verhandlung"}, {"value": "won", "label": "Gewonnen"}, {"value": "lost", "label": "Verloren"}]'::jsonb,
     false, ARRAY['role']),
    ('territory', 'Gebiet', 'Vertriebsgebiet', 'text', NULL, false, ARRAY['user'])
ON CONFLICT (name) DO NOTHING;

-- =====================================================
-- GRANTS
-- =====================================================

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."user_attributes" TO "authenticated";
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."role_attributes" TO "authenticated";
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."permission_conditions" TO "authenticated";
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."attribute_definitions" TO "authenticated";

GRANT ALL ON TABLE "public"."user_attributes" TO "service_role";
GRANT ALL ON TABLE "public"."role_attributes" TO "service_role";
GRANT ALL ON TABLE "public"."permission_conditions" TO "service_role";
GRANT ALL ON TABLE "public"."attribute_definitions" TO "service_role";

-- =====================================================
-- RLS POLICIES
-- =====================================================

-- User Attributes: Eigene lesen, Admins alles
DROP POLICY IF EXISTS "User attributes read own" ON "public"."user_attributes";
CREATE POLICY "User attributes read own" ON "public"."user_attributes"
    FOR SELECT TO authenticated
    USING (
        public.is_admin() 
        OR sales_id = public.get_current_sales_id()
    );

DROP POLICY IF EXISTS "User attributes write admin" ON "public"."user_attributes";
CREATE POLICY "User attributes write admin" ON "public"."user_attributes"
    FOR ALL TO authenticated
    USING (public.is_admin())
    WITH CHECK (public.is_admin());

-- Role Attributes: Lesen für alle, Schreiben für Admins
DROP POLICY IF EXISTS "Role attributes read" ON "public"."role_attributes";
CREATE POLICY "Role attributes read" ON "public"."role_attributes"
    FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Role attributes write admin" ON "public"."role_attributes";
CREATE POLICY "Role attributes write admin" ON "public"."role_attributes"
    FOR ALL TO authenticated
    USING (public.is_admin())
    WITH CHECK (public.is_admin());

-- Permission Conditions: Lesen für alle, Schreiben für Admins
DROP POLICY IF EXISTS "Permission conditions read" ON "public"."permission_conditions";
CREATE POLICY "Permission conditions read" ON "public"."permission_conditions"
    FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Permission conditions write admin" ON "public"."permission_conditions";
CREATE POLICY "Permission conditions write admin" ON "public"."permission_conditions"
    FOR ALL TO authenticated
    USING (public.is_admin())
    WITH CHECK (public.is_admin());

-- Attribute Definitions: Lesen für alle, Schreiben für Admins
DROP POLICY IF EXISTS "Attribute definitions read" ON "public"."attribute_definitions";
CREATE POLICY "Attribute definitions read" ON "public"."attribute_definitions"
    FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Attribute definitions write admin" ON "public"."attribute_definitions";
CREATE POLICY "Attribute definitions write admin" ON "public"."attribute_definitions"
    FOR ALL TO authenticated
    USING (public.is_admin())
    WITH CHECK (public.is_admin());

-- =====================================================
-- VIEW FÜR BENUTZER MIT ATTRIBUTEN
-- =====================================================

DROP VIEW IF EXISTS "public"."user_with_attributes";
CREATE VIEW "public"."user_with_attributes"
WITH (security_invoker=on)
AS
SELECT 
    s.id as sales_id,
    s.first_name,
    s.last_name,
    s.email,
    s.administrator,
    r.id as role_id,
    r.name as role_name,
    COALESCE(
        (SELECT jsonb_object_agg(ua.attribute_name, ua.attribute_value)
         FROM public.user_attributes ua 
         WHERE ua.sales_id = s.id),
        '{}'::jsonb
    ) as user_attributes,
    COALESCE(
        (SELECT jsonb_object_agg(ra.attribute_name, 
            (SELECT jsonb_agg(ra2.attribute_value) 
             FROM public.role_attributes ra2 
             WHERE ra2.role_id = r.id AND ra2.attribute_name = ra.attribute_name))
         FROM public.role_attributes ra 
         WHERE ra.role_id = r.id
         GROUP BY ra.role_id),
        '{}'::jsonb
    ) as role_attributes
FROM public.sales s
LEFT JOIN public.roles r ON s.role_id = r.id;

GRANT SELECT ON "public"."user_with_attributes" TO "authenticated";
