-- Migration: Custom Objects, RBAC, Audit Logs, Soft Delete, Versioning
-- Date: 2026-02-23

-- ============================================
-- 1. SOFT DELETE - deleted_at column on main tables
-- ============================================

ALTER TABLE contacts ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ DEFAULT NULL;
CREATE INDEX IF NOT EXISTS idx_contacts_deleted_at ON contacts(deleted_at);

ALTER TABLE companies ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ DEFAULT NULL;
CREATE INDEX IF NOT EXISTS idx_companies_deleted_at ON companies(deleted_at);

ALTER TABLE deals ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ DEFAULT NULL;
CREATE INDEX IF NOT EXISTS idx_deals_deleted_at ON deals(deleted_at);

ALTER TABLE tasks ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ DEFAULT NULL;
CREATE INDEX IF NOT EXISTS idx_tasks_deleted_at ON tasks(deleted_at);

ALTER TABLE contact_notes ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ DEFAULT NULL;
CREATE INDEX IF NOT EXISTS idx_contact_notes_deleted_at ON contact_notes(deleted_at);

ALTER TABLE deal_notes ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ DEFAULT NULL;
CREATE INDEX IF NOT EXISTS idx_deal_notes_deleted_at ON deal_notes(deleted_at);

-- ============================================
-- 2. Update contacts_summary view to include deleted_at
-- ============================================

DROP VIEW IF EXISTS contacts_summary;

CREATE VIEW contacts_summary AS
SELECT
    co.id,
    co.first_name,
    co.last_name,
    co.gender,
    co.title,
    co.email_jsonb,
    jsonb_path_query_array(co.email_jsonb, '$[*].email')::text AS email_fts,
    co.phone_jsonb,
    jsonb_path_query_array(co.phone_jsonb, '$[*].number')::text AS phone_fts,
    co.background,
    co.avatar,
    co.first_seen,
    co.last_seen,
    co.has_newsletter,
    co.status,
    co.tags,
    co.company_id,
    co.sales_id,
    co.linkedin_url,
    co.deleted_at,
    c.name AS company_name,
    count(distinct t.id) AS nb_tasks
FROM
    contacts co
LEFT JOIN
    tasks t ON co.id = t.contact_id
LEFT JOIN
    companies c ON co.company_id = c.id
GROUP BY
    co.id, c.name;

-- ============================================
-- 2b. Update companies_summary view to include deleted_at
-- ============================================

DROP VIEW IF EXISTS companies_summary;

CREATE VIEW companies_summary AS
SELECT
    c.id,
    c.created_at,
    c.name,
    c.sector,
    c.size,
    c.linkedin_url,
    c.website,
    c.phone_number,
    c.address,
    c.zipcode,
    c.city,
    c.state_abbr,
    c.sales_id,
    c.context_links,
    c.country,
    c.description,
    c.revenue,
    c.tax_identifier,
    c.logo,
    c.deleted_at,
    count(distinct d.id) AS nb_deals,
    count(distinct co.id) AS nb_contacts
FROM
    companies c
LEFT JOIN
    deals d ON c.id = d.company_id
LEFT JOIN
    contacts co ON c.id = co.company_id
GROUP BY
    c.id;

-- ============================================
-- 3. RBAC: Roles & Teams
-- ============================================

CREATE TABLE IF NOT EXISTS "public"."roles" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "description" text,
    "created_at" timestamp with time zone default now() not null,
    "updated_at" timestamp with time zone default now() not null,
    constraint roles_pkey primary key (id)
);

ALTER TABLE "public"."roles" ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
CREATE POLICY "roles_select_policy" ON "public"."roles"
    FOR SELECT USING (auth.role() = 'authenticated');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
CREATE POLICY "roles_modify_policy" ON "public"."roles"
    FOR ALL USING (auth.role() = 'authenticated');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS "public"."role_permissions" (
    "id" bigint generated by default as identity not null,
    "role_id" bigint not null references roles(id) on delete cascade,
    "resource" text not null,
    "action" text not null,
    "scope" text default 'none' not null,
    "conditions" jsonb,
    "created_at" timestamp with time zone default now() not null,
    constraint role_permissions_pkey primary key (id)
);

ALTER TABLE "public"."role_permissions" ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
CREATE POLICY "role_permissions_select_policy" ON "public"."role_permissions"
    FOR SELECT USING (auth.role() = 'authenticated');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
CREATE POLICY "role_permissions_modify_policy" ON "public"."role_permissions"
    FOR ALL USING (auth.role() = 'authenticated');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS "public"."teams" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "description" text,
    "created_at" timestamp with time zone default now() not null,
    constraint teams_pkey primary key (id)
);

ALTER TABLE "public"."teams" ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
CREATE POLICY "teams_select_policy" ON "public"."teams"
    FOR SELECT USING (auth.role() = 'authenticated');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
CREATE POLICY "teams_modify_policy" ON "public"."teams"
    FOR ALL USING (auth.role() = 'authenticated');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS "public"."team_members" (
    "id" bigint generated by default as identity not null,
    "team_id" bigint not null references teams(id) on delete cascade,
    "sales_id" bigint not null references sales(id) on delete cascade,
    "is_leader" boolean default false not null,
    "created_at" timestamp with time zone default now() not null,
    constraint team_members_pkey primary key (id),
    constraint team_members_unique unique (team_id, sales_id)
);

ALTER TABLE "public"."team_members" ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
CREATE POLICY "team_members_select_policy" ON "public"."team_members"
    FOR SELECT USING (auth.role() = 'authenticated');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
CREATE POLICY "team_members_modify_policy" ON "public"."team_members"
    FOR ALL USING (auth.role() = 'authenticated');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ============================================
-- 4. Relationship Definitions
-- ============================================

CREATE TABLE IF NOT EXISTS "public"."relationship_definitions" (
    "id" bigint generated by default as identity not null,
    "source_object_type" text not null,
    "target_object_type" text not null,
    "relationship_name" text not null,
    "inverse_name" text,
    "cardinality" text default 'many-to-many' not null,
    "created_at" timestamp with time zone default now() not null,
    constraint relationship_definitions_pkey primary key (id)
);

ALTER TABLE "public"."relationship_definitions" ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
CREATE POLICY "relationship_definitions_policy" ON "public"."relationship_definitions"
    FOR ALL USING (auth.role() = 'authenticated');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS idx_relationship_definitions_source ON relationship_definitions(source_object_type);
CREATE INDEX IF NOT EXISTS idx_relationship_definitions_target ON relationship_definitions(target_object_type);

-- ============================================
-- 5. Custom Object Definitions
-- ============================================

CREATE TABLE IF NOT EXISTS "public"."custom_object_definitions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now() not null,
    "updated_at" timestamp with time zone default now() not null,
    "name" text not null,
    "label" text not null,
    "label_plural" text not null,
    "description" text,
    "icon" text default 'box' not null,
    "color" text default '#6366f1' not null,
    "is_active" boolean default true not null,
    "allow_attachments" boolean default true not null,
    "allow_notes" boolean default true not null,
    "allow_tasks" boolean default false not null,
    "sort_order" integer default 0 not null,
    "deleted_at" timestamp with time zone,
    constraint custom_object_definitions_pkey primary key (id),
    constraint custom_object_definitions_name_key unique (name)
);

ALTER TABLE "public"."custom_object_definitions" ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
CREATE POLICY "custom_object_definitions_policy" ON "public"."custom_object_definitions"
    FOR ALL USING (auth.role() = 'authenticated');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ============================================
-- 6. Custom Field Definitions
-- ============================================

CREATE TABLE IF NOT EXISTS "public"."custom_field_definitions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now() not null,
    "updated_at" timestamp with time zone default now() not null,
    "custom_object_id" bigint references custom_object_definitions(id) on delete cascade,
    "entity_type" text check (entity_type in ('contacts', 'companies', 'deals')),
    "name" text not null,
    "label" text not null,
    "description" text,
    "field_type" text not null default 'text',
    "is_required" boolean default false not null,
    "is_unique" boolean default false not null,
    "default_value" text,
    "options" jsonb,
    "reference_object" text,
    "reference_display_field" text,
    "validation_rules" jsonb,
    "placeholder" text,
    "help_text" text,
    "show_in_list" boolean default true not null,
    "show_in_detail" boolean default true not null,
    "column_width" integer default 150,
    "sort_order" integer default 0 not null,
    "field_group" text,
    "deleted_at" timestamp with time zone,
    constraint custom_field_definitions_pkey primary key (id)
);

ALTER TABLE "public"."custom_field_definitions" ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
CREATE POLICY "custom_field_definitions_policy" ON "public"."custom_field_definitions"
    FOR ALL USING (auth.role() = 'authenticated');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ============================================
-- 7. Custom Object Data
-- ============================================

CREATE TABLE IF NOT EXISTS "public"."custom_object_data" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now() not null,
    "updated_at" timestamp with time zone default now() not null,
    "object_definition_id" bigint not null references custom_object_definitions(id) on delete cascade,
    "data" jsonb default '{}'::jsonb not null,
    "sales_id" bigint references sales(id),
    "deleted_at" timestamp with time zone,
    constraint custom_object_data_pkey primary key (id)
);

ALTER TABLE "public"."custom_object_data" ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
CREATE POLICY "custom_object_data_policy" ON "public"."custom_object_data"
    FOR ALL USING (auth.role() = 'authenticated');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ============================================
-- 8. Custom Field Values
-- ============================================

CREATE TABLE IF NOT EXISTS "public"."custom_field_values" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now() not null,
    "updated_at" timestamp with time zone default now() not null,
    "field_definition_id" bigint not null references custom_field_definitions(id) on delete cascade,
    "contact_id" bigint references contacts(id) on delete cascade,
    "company_id" bigint references companies(id) on delete cascade,
    "deal_id" bigint references deals(id) on delete cascade,
    "custom_object_data_id" bigint references custom_object_data(id) on delete cascade,
    "value" jsonb,
    constraint custom_field_values_pkey primary key (id)
);

ALTER TABLE "public"."custom_field_values" ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
CREATE POLICY "custom_field_values_policy" ON "public"."custom_field_values"
    FOR ALL USING (auth.role() = 'authenticated');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ============================================
-- 9. Object Relationships
-- ============================================

CREATE TABLE IF NOT EXISTS "public"."object_relationships" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now() not null,
    "source_type" text not null,
    "source_id" bigint not null,
    "target_type" text not null,
    "target_id" bigint not null,
    "relationship_type" text,
    "metadata" jsonb,
    constraint object_relationships_pkey primary key (id)
);

ALTER TABLE "public"."object_relationships" ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
CREATE POLICY "object_relationships_policy" ON "public"."object_relationships"
    FOR ALL USING (auth.role() = 'authenticated');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ============================================
-- 10. Audit Logs
-- ============================================

DO $$ BEGIN
CREATE TYPE audit_action_type AS ENUM (
  'create', 'update', 'delete', 'restore',
  'export', 'import', 'merge',
  'bulk_delete', 'bulk_update'
);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS "public"."audit_logs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now() not null,
    "user_id" uuid references auth.users(id) on delete set null,
    "user_email" text,
    "user_name" text,
    "action" audit_action_type not null,
    "resource_type" text not null,
    "resource_id" bigint,
    "resource_name" text,
    "old_values" jsonb,
    "new_values" jsonb,
    "changed_fields" text[],
    "metadata" jsonb,
    "ip_address" inet,
    "user_agent" text,
    "batch_id" uuid,
    "affected_count" integer default 1,
    constraint audit_logs_pkey primary key (id)
);

ALTER TABLE "public"."audit_logs" ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
CREATE POLICY "audit_logs_select_admin" ON "public"."audit_logs"
    FOR SELECT TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM sales
            WHERE sales.user_id = auth.uid()
            AND sales.administrator = true
        )
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
CREATE POLICY "audit_logs_select_own" ON "public"."audit_logs"
    FOR SELECT TO authenticated
    USING (user_id = auth.uid());
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
CREATE POLICY "audit_logs_insert" ON "public"."audit_logs"
    FOR INSERT TO authenticated
    WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ============================================
-- 11. Record Versions
-- ============================================

CREATE TABLE IF NOT EXISTS "public"."record_versions" (
    "id" bigint generated by default as identity not null,
    "version_number" integer not null,
    "created_at" timestamp with time zone default now() not null,
    "created_by" uuid references auth.users(id) on delete set null,
    "created_by_email" text,
    "resource_type" text not null,
    "resource_id" bigint not null,
    "data" jsonb not null,
    "change_summary" text,
    constraint record_versions_pkey primary key (id),
    constraint record_versions_unique unique (resource_type, resource_id, version_number)
);

ALTER TABLE "public"."record_versions" ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
CREATE POLICY "record_versions_select" ON "public"."record_versions"
    FOR SELECT TO authenticated
    USING (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
CREATE POLICY "record_versions_insert" ON "public"."record_versions"
    FOR INSERT TO authenticated
    WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ============================================
-- 12. Indexes
-- ============================================

CREATE INDEX IF NOT EXISTS idx_role_permissions_role ON role_permissions(role_id);
CREATE INDEX IF NOT EXISTS idx_team_members_team ON team_members(team_id);
CREATE INDEX IF NOT EXISTS idx_team_members_sales ON team_members(sales_id);
CREATE INDEX IF NOT EXISTS idx_custom_field_definitions_object ON custom_field_definitions(custom_object_id);
CREATE INDEX IF NOT EXISTS idx_custom_field_definitions_entity ON custom_field_definitions(entity_type);
CREATE INDEX IF NOT EXISTS idx_custom_field_values_contact ON custom_field_values(contact_id);
CREATE INDEX IF NOT EXISTS idx_custom_field_values_company ON custom_field_values(company_id);
CREATE INDEX IF NOT EXISTS idx_custom_field_values_deal ON custom_field_values(deal_id);
CREATE INDEX IF NOT EXISTS idx_custom_field_values_field ON custom_field_values(field_definition_id);
CREATE INDEX IF NOT EXISTS idx_custom_object_data_definition ON custom_object_data(object_definition_id);
CREATE INDEX IF NOT EXISTS idx_object_relationships_source ON object_relationships(source_type, source_id);
CREATE INDEX IF NOT EXISTS idx_object_relationships_target ON object_relationships(target_type, target_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id ON audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs(action);
CREATE INDEX IF NOT EXISTS idx_audit_logs_resource ON audit_logs(resource_type, resource_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_batch_id ON audit_logs(batch_id) WHERE batch_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_record_versions_resource ON record_versions(resource_type, resource_id);
CREATE INDEX IF NOT EXISTS idx_record_versions_created_at ON record_versions(created_at DESC);
