-- Migration: ABAC (Attribute-Based Access Control) Tables
-- Date: 2026-02-26
-- Creates tables for attribute definitions, user attributes, and permission conditions

-- ============================================
-- 1. ATTRIBUTE DEFINITIONS
-- Vordefinierte Attribute wie Region, Abteilung, etc.
-- ============================================

CREATE TABLE IF NOT EXISTS "public"."attribute_definitions" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "label" text not null,
    "description" text,
    "data_type" text not null default 'text',
    "allowed_values" jsonb,
    "is_system" boolean default false not null,
    "applies_to" text[] default '{user}' not null,
    "created_at" timestamp with time zone default now() not null,
    constraint attribute_definitions_pkey primary key (id),
    constraint attribute_definitions_name_key unique (name),
    constraint attribute_definitions_data_type_check check (data_type in ('text', 'number', 'boolean', 'date', 'select'))
);

ALTER TABLE "public"."attribute_definitions" ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
CREATE POLICY "attribute_definitions_select_policy" ON "public"."attribute_definitions"
    FOR SELECT USING (auth.role() = 'authenticated');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
CREATE POLICY "attribute_definitions_modify_policy" ON "public"."attribute_definitions"
    FOR ALL USING (auth.role() = 'authenticated');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS idx_attribute_definitions_name ON attribute_definitions(name);

-- ============================================
-- 2. USER ATTRIBUTES
-- Benutzerattribute (z.B. User X hat Region = "DACH")
-- ============================================

CREATE TABLE IF NOT EXISTS "public"."user_attributes" (
    "id" bigint generated by default as identity not null,
    "sales_id" bigint not null references sales(id) on delete cascade,
    "attribute_name" text not null,
    "attribute_value" text not null,
    "created_at" timestamp with time zone default now() not null,
    "updated_at" timestamp with time zone default now() not null,
    constraint user_attributes_pkey primary key (id),
    constraint user_attributes_unique unique (sales_id, attribute_name)
);

ALTER TABLE "public"."user_attributes" ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
CREATE POLICY "user_attributes_select_policy" ON "public"."user_attributes"
    FOR SELECT USING (auth.role() = 'authenticated');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
CREATE POLICY "user_attributes_modify_policy" ON "public"."user_attributes"
    FOR ALL USING (auth.role() = 'authenticated');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS idx_user_attributes_sales_id ON user_attributes(sales_id);
CREATE INDEX IF NOT EXISTS idx_user_attributes_attribute_name ON user_attributes(attribute_name);

-- ============================================
-- 3. PERMISSION CONDITIONS
-- ABAC-Bedingungen für Berechtigungen
-- ============================================

CREATE TABLE IF NOT EXISTS "public"."permission_conditions" (
    "id" bigint generated by default as identity not null,
    "role_permission_id" bigint not null references role_permissions(id) on delete cascade,
    "condition_type" text not null default 'field_value',
    "target_field" text not null,
    "operator" text not null default '=',
    "source_type" text not null default 'static_value',
    "source_attribute" text,
    "static_values" text[],
    "logic_operator" text default 'AND' not null,
    "is_active" boolean default true not null,
    "created_at" timestamp with time zone default now() not null,
    constraint permission_conditions_pkey primary key (id),
    constraint permission_conditions_condition_type_check check (condition_type in ('attribute_match', 'field_value', 'custom_expression')),
    constraint permission_conditions_operator_check check (operator in ('=', '!=', '>', '<', '>=', '<=', 'IN', 'NOT IN', 'LIKE', 'ILIKE', 'IS NULL', 'IS NOT NULL', 'CONTAINS')),
    constraint permission_conditions_source_type_check check (source_type in ('user_attribute', 'role_attribute', 'static_value', 'current_user')),
    constraint permission_conditions_logic_operator_check check (logic_operator in ('AND', 'OR'))
);

ALTER TABLE "public"."permission_conditions" ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
CREATE POLICY "permission_conditions_select_policy" ON "public"."permission_conditions"
    FOR SELECT USING (auth.role() = 'authenticated');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
CREATE POLICY "permission_conditions_modify_policy" ON "public"."permission_conditions"
    FOR ALL USING (auth.role() = 'authenticated');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS idx_permission_conditions_role_permission_id ON permission_conditions(role_permission_id);
CREATE INDEX IF NOT EXISTS idx_permission_conditions_is_active ON permission_conditions(is_active);
