-- ============================================
-- user_roles: Assign users (sales) to roles
-- ============================================

CREATE TABLE IF NOT EXISTS "public"."user_roles" (
    "id" bigint generated by default as identity not null,
    "sales_id" bigint not null references sales(id) on delete cascade,
    "role_id" bigint not null references roles(id) on delete cascade,
    "created_at" timestamp with time zone default now() not null,
    constraint user_roles_pkey primary key (id),
    constraint user_roles_unique unique (sales_id, role_id)
);

ALTER TABLE "public"."user_roles" ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
CREATE POLICY "user_roles_select_policy" ON "public"."user_roles"
    FOR SELECT USING (auth.role() = 'authenticated');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
CREATE POLICY "user_roles_modify_policy" ON "public"."user_roles"
    FOR ALL USING (auth.role() = 'authenticated');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ============================================
-- team_roles: Assign teams to roles
-- ============================================

CREATE TABLE IF NOT EXISTS "public"."team_roles" (
    "id" bigint generated by default as identity not null,
    "team_id" bigint not null references teams(id) on delete cascade,
    "role_id" bigint not null references roles(id) on delete cascade,
    "created_at" timestamp with time zone default now() not null,
    constraint team_roles_pkey primary key (id),
    constraint team_roles_unique unique (team_id, role_id)
);

ALTER TABLE "public"."team_roles" ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
CREATE POLICY "team_roles_select_policy" ON "public"."team_roles"
    FOR SELECT USING (auth.role() = 'authenticated');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
CREATE POLICY "team_roles_modify_policy" ON "public"."team_roles"
    FOR ALL USING (auth.role() = 'authenticated');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_user_roles_sales ON user_roles(sales_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_role ON user_roles(role_id);
CREATE INDEX IF NOT EXISTS idx_team_roles_team ON team_roles(team_id);
CREATE INDEX IF NOT EXISTS idx_team_roles_role ON team_roles(role_id);
