-- Migration: Custom Objects und Custom Fields System
-- Ermöglicht das Erstellen eigener Objekte und Felder über die Admin-Oberfläche

-- =====================================================
-- 1. CUSTOM OBJECT DEFINITIONS (Objekttyp-Definitionen)
-- =====================================================

CREATE TABLE IF NOT EXISTS public.custom_object_definitions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  
  -- Basis-Informationen
  name text NOT NULL,                    -- Technischer Name (z.B. "project")
  label text NOT NULL,                   -- Anzeigename (z.B. "Projekt")
  label_plural text NOT NULL,            -- Plural (z.B. "Projekte")
  description text,
  icon text DEFAULT 'box',               -- Lucide Icon Name
  color text DEFAULT '#6366f1',          -- Farbe für UI
  
  -- Konfiguration
  is_active boolean NOT NULL DEFAULT true,
  allow_attachments boolean DEFAULT true,
  allow_notes boolean DEFAULT true,
  allow_tasks boolean DEFAULT false,
  
  -- Sortierung
  sort_order integer DEFAULT 0,
  
  -- Soft Delete
  deleted_at timestamptz,
  
  CONSTRAINT custom_object_definitions_name_unique UNIQUE (name)
);

ALTER TABLE public.custom_object_definitions ENABLE ROW LEVEL SECURITY;

CREATE INDEX idx_custom_object_definitions_name ON public.custom_object_definitions(name);
CREATE INDEX idx_custom_object_definitions_active ON public.custom_object_definitions(is_active) WHERE deleted_at IS NULL;

-- =====================================================
-- 2. CUSTOM FIELD DEFINITIONS (Feld-Definitionen)
-- =====================================================

CREATE TABLE IF NOT EXISTS public.custom_field_definitions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  
  -- Zuordnung: entweder zu Custom Object ODER zu Standard-Entity
  custom_object_id bigint REFERENCES public.custom_object_definitions(id) ON DELETE CASCADE,
  entity_type text,                      -- 'contacts', 'companies', 'deals' oder NULL für Custom Objects
  
  -- Feld-Definition
  name text NOT NULL,                    -- Technischer Feldname (z.B. "budget")
  label text NOT NULL,                   -- Anzeigename (z.B. "Budget")
  description text,
  
  -- Feldtyp und Validierung
  field_type text NOT NULL DEFAULT 'text',  -- text, number, date, datetime, boolean, select, multiselect, reference, email, phone, url, textarea, currency
  is_required boolean DEFAULT false,
  is_unique boolean DEFAULT false,
  default_value text,
  
  -- Optionen für Select/Multiselect
  options jsonb,                         -- [{"value": "opt1", "label": "Option 1"}, ...]
  
  -- Reference-Konfiguration (für Verknüpfungen)
  reference_object text,                 -- 'contacts', 'companies', 'deals' oder custom_object name
  reference_display_field text,          -- Welches Feld anzeigen (z.B. "name", "first_name")
  
  -- Validierung
  validation_rules jsonb,                -- {"min": 0, "max": 100, "pattern": "...", "min_length": 5}
  
  -- UI-Konfiguration
  placeholder text,
  help_text text,
  show_in_list boolean DEFAULT true,     -- In Listenansicht anzeigen
  show_in_detail boolean DEFAULT true,   -- In Detailansicht anzeigen
  column_width integer,                  -- Spaltenbreite in px
  sort_order integer DEFAULT 0,
  
  -- Gruppierung
  field_group text,                      -- Optional: Gruppe für Tabs/Sections
  
  -- Soft Delete
  deleted_at timestamptz,
  
  CONSTRAINT custom_field_unique_per_object UNIQUE (custom_object_id, name) WHERE entity_type IS NULL,
  CONSTRAINT custom_field_unique_per_entity UNIQUE (entity_type, name) WHERE custom_object_id IS NULL,
  CONSTRAINT custom_field_type_check CHECK (
    field_type IN ('text', 'number', 'date', 'datetime', 'boolean', 'select', 'multiselect', 'reference', 'email', 'phone', 'url', 'textarea', 'currency', 'percent', 'rating')
  )
);

ALTER TABLE public.custom_field_definitions ENABLE ROW LEVEL SECURITY;

CREATE INDEX idx_custom_field_definitions_object ON public.custom_field_definitions(custom_object_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_custom_field_definitions_entity ON public.custom_field_definitions(entity_type) WHERE deleted_at IS NULL;

-- =====================================================
-- 3. CUSTOM OBJECT DATA (Datenspeicher für Custom Objects)
-- =====================================================

CREATE TABLE IF NOT EXISTS public.custom_object_data (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  
  -- Zuordnung zum Objekttyp
  object_definition_id bigint NOT NULL REFERENCES public.custom_object_definitions(id) ON DELETE CASCADE,
  
  -- Dynamische Felddaten als JSONB
  data jsonb NOT NULL DEFAULT '{}',
  
  -- Standard-Felder für RBAC
  sales_id bigint REFERENCES public.sales(id),
  
  -- Soft Delete
  deleted_at timestamptz
);

ALTER TABLE public.custom_object_data ENABLE ROW LEVEL SECURITY;

CREATE INDEX idx_custom_object_data_definition ON public.custom_object_data(object_definition_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_custom_object_data_sales ON public.custom_object_data(sales_id);
CREATE INDEX idx_custom_object_data_jsonb ON public.custom_object_data USING GIN (data);

-- =====================================================
-- 4. CUSTOM FIELD VALUES (Werte für Custom Fields auf Standard-Entities)
-- =====================================================

CREATE TABLE IF NOT EXISTS public.custom_field_values (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  
  -- Zuordnung zum Feld
  field_definition_id bigint NOT NULL REFERENCES public.custom_field_definitions(id) ON DELETE CASCADE,
  
  -- Zuordnung zur Entity (eine davon muss gesetzt sein)
  contact_id bigint REFERENCES public.contacts(id) ON DELETE CASCADE,
  company_id bigint REFERENCES public.companies(id) ON DELETE CASCADE,
  deal_id bigint REFERENCES public.deals(id) ON DELETE CASCADE,
  
  -- Wert (als JSONB für Flexibilität)
  value jsonb,
  
  CONSTRAINT custom_field_values_single_entity CHECK (
    (contact_id IS NOT NULL)::int + (company_id IS NOT NULL)::int + (deal_id IS NOT NULL)::int = 1
  )
);

ALTER TABLE public.custom_field_values ENABLE ROW LEVEL SECURITY;

CREATE INDEX idx_custom_field_values_field ON public.custom_field_values(field_definition_id);
CREATE INDEX idx_custom_field_values_contact ON public.custom_field_values(contact_id) WHERE contact_id IS NOT NULL;
CREATE INDEX idx_custom_field_values_company ON public.custom_field_values(company_id) WHERE company_id IS NOT NULL;
CREATE INDEX idx_custom_field_values_deal ON public.custom_field_values(deal_id) WHERE deal_id IS NOT NULL;

-- Unique constraint: Ein Feld pro Entity
CREATE UNIQUE INDEX idx_custom_field_values_unique_contact ON public.custom_field_values(field_definition_id, contact_id) WHERE contact_id IS NOT NULL;
CREATE UNIQUE INDEX idx_custom_field_values_unique_company ON public.custom_field_values(field_definition_id, company_id) WHERE company_id IS NOT NULL;
CREATE UNIQUE INDEX idx_custom_field_values_unique_deal ON public.custom_field_values(field_definition_id, deal_id) WHERE deal_id IS NOT NULL;

-- =====================================================
-- 5. OBJECT RELATIONSHIPS (M:N Verknüpfungen)
-- =====================================================

CREATE TABLE IF NOT EXISTS public.object_relationships (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  
  -- Quell-Objekt
  source_type text NOT NULL,             -- 'contacts', 'companies', 'deals' oder custom_object name
  source_id bigint NOT NULL,
  
  -- Ziel-Objekt
  target_type text NOT NULL,
  target_id bigint NOT NULL,
  
  -- Beziehungstyp (optional)
  relationship_type text,                -- z.B. "parent", "related", "depends_on"
  
  -- Metadaten
  metadata jsonb,
  
  CONSTRAINT object_relationships_unique UNIQUE (source_type, source_id, target_type, target_id)
);

ALTER TABLE public.object_relationships ENABLE ROW LEVEL SECURITY;

CREATE INDEX idx_object_relationships_source ON public.object_relationships(source_type, source_id);
CREATE INDEX idx_object_relationships_target ON public.object_relationships(target_type, target_id);

-- =====================================================
-- 6. RLS POLICIES
-- =====================================================

-- Custom Object Definitions: Lesen für alle, Schreiben nur für Admins
CREATE POLICY "Custom object definitions read for authenticated" ON public.custom_object_definitions
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Custom object definitions write for admins" ON public.custom_object_definitions
  FOR ALL TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

-- Custom Field Definitions: Lesen für alle, Schreiben nur für Admins
CREATE POLICY "Custom field definitions read for authenticated" ON public.custom_field_definitions
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Custom field definitions write for admins" ON public.custom_field_definitions
  FOR ALL TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

-- Custom Object Data: RBAC-basiert
CREATE POLICY "Custom object data read with RBAC" ON public.custom_object_data
  FOR SELECT TO authenticated
  USING (
    public.is_admin()
    OR public.has_record_access('custom_objects', 'list', sales_id)
  );

CREATE POLICY "Custom object data insert with RBAC" ON public.custom_object_data
  FOR INSERT TO authenticated
  WITH CHECK (
    public.is_admin()
    OR public.check_permission('custom_objects', 'create') IN ('all', 'own', 'team')
  );

CREATE POLICY "Custom object data update with RBAC" ON public.custom_object_data
  FOR UPDATE TO authenticated
  USING (
    public.is_admin()
    OR public.has_record_access('custom_objects', 'edit', sales_id)
  );

CREATE POLICY "Custom object data delete with RBAC" ON public.custom_object_data
  FOR DELETE TO authenticated
  USING (
    public.is_admin()
    OR public.has_record_access('custom_objects', 'delete', sales_id)
  );

-- Custom Field Values: Basierend auf Entity-Zugriff
CREATE POLICY "Custom field values read for authenticated" ON public.custom_field_values
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Custom field values write for authenticated" ON public.custom_field_values
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Object Relationships: Für alle authentifizierten Benutzer
CREATE POLICY "Object relationships read for authenticated" ON public.object_relationships
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Object relationships write for authenticated" ON public.object_relationships
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- =====================================================
-- 7. GRANTS
-- =====================================================

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.custom_object_definitions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.custom_field_definitions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.custom_object_data TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.custom_field_values TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.object_relationships TO authenticated;

GRANT USAGE, SELECT ON SEQUENCE public.custom_object_definitions_id_seq TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.custom_field_definitions_id_seq TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.custom_object_data_id_seq TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.custom_field_values_id_seq TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.object_relationships_id_seq TO authenticated;

-- =====================================================
-- 8. HILFSFUNKTIONEN
-- =====================================================

-- Funktion um Custom Field Values für eine Entity zu laden
CREATE OR REPLACE FUNCTION public.get_custom_field_values(
  p_entity_type text,
  p_entity_id bigint
)
RETURNS jsonb
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
  SELECT COALESCE(
    jsonb_object_agg(
      cfd.name,
      cfv.value
    ),
    '{}'::jsonb
  )
  FROM public.custom_field_definitions cfd
  LEFT JOIN public.custom_field_values cfv ON cfv.field_definition_id = cfd.id
    AND (
      (p_entity_type = 'contacts' AND cfv.contact_id = p_entity_id) OR
      (p_entity_type = 'companies' AND cfv.company_id = p_entity_id) OR
      (p_entity_type = 'deals' AND cfv.deal_id = p_entity_id)
    )
  WHERE cfd.entity_type = p_entity_type
    AND cfd.deleted_at IS NULL
$$;

-- Funktion um Custom Field Value zu setzen/aktualisieren
CREATE OR REPLACE FUNCTION public.set_custom_field_value(
  p_entity_type text,
  p_entity_id bigint,
  p_field_name text,
  p_value jsonb
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_field_id bigint;
BEGIN
  -- Feld-ID ermitteln
  SELECT id INTO v_field_id
  FROM public.custom_field_definitions
  WHERE entity_type = p_entity_type
    AND name = p_field_name
    AND deleted_at IS NULL;
  
  IF v_field_id IS NULL THEN
    RETURN false;
  END IF;
  
  -- Upsert basierend auf Entity-Typ
  IF p_entity_type = 'contacts' THEN
    INSERT INTO public.custom_field_values (field_definition_id, contact_id, value)
    VALUES (v_field_id, p_entity_id, p_value)
    ON CONFLICT (field_definition_id, contact_id) 
    DO UPDATE SET value = p_value, updated_at = NOW();
  ELSIF p_entity_type = 'companies' THEN
    INSERT INTO public.custom_field_values (field_definition_id, company_id, value)
    VALUES (v_field_id, p_entity_id, p_value)
    ON CONFLICT (field_definition_id, company_id) 
    DO UPDATE SET value = p_value, updated_at = NOW();
  ELSIF p_entity_type = 'deals' THEN
    INSERT INTO public.custom_field_values (field_definition_id, deal_id, value)
    VALUES (v_field_id, p_entity_id, p_value)
    ON CONFLICT (field_definition_id, deal_id) 
    DO UPDATE SET value = p_value, updated_at = NOW();
  ELSE
    RETURN false;
  END IF;
  
  RETURN true;
END;
$$;

-- =====================================================
-- 9. VIEWS
-- =====================================================

-- View für Custom Objects mit allen Feldern
CREATE OR REPLACE VIEW public.custom_objects_with_fields AS
SELECT 
  cod.id,
  cod.name,
  cod.label,
  cod.label_plural,
  cod.description,
  cod.icon,
  cod.color,
  cod.is_active,
  cod.allow_attachments,
  cod.allow_notes,
  cod.allow_tasks,
  cod.sort_order,
  cod.created_at,
  cod.updated_at,
  COALESCE(
    jsonb_agg(
      jsonb_build_object(
        'id', cfd.id,
        'name', cfd.name,
        'label', cfd.label,
        'field_type', cfd.field_type,
        'is_required', cfd.is_required,
        'options', cfd.options,
        'sort_order', cfd.sort_order
      ) ORDER BY cfd.sort_order
    ) FILTER (WHERE cfd.id IS NOT NULL),
    '[]'::jsonb
  ) as fields
FROM public.custom_object_definitions cod
LEFT JOIN public.custom_field_definitions cfd 
  ON cfd.custom_object_id = cod.id AND cfd.deleted_at IS NULL
WHERE cod.deleted_at IS NULL
GROUP BY cod.id;

-- =====================================================
-- 10. KOMMENTARE
-- =====================================================

COMMENT ON TABLE public.custom_object_definitions IS 'Definitionen für benutzerdefinierte Objekte';
COMMENT ON TABLE public.custom_field_definitions IS 'Definitionen für benutzerdefinierte Felder';
COMMENT ON TABLE public.custom_object_data IS 'Datensätze für benutzerdefinierte Objekte';
COMMENT ON TABLE public.custom_field_values IS 'Feldwerte für benutzerdefinierte Felder auf Standard-Entities';
COMMENT ON TABLE public.object_relationships IS 'M:N Verknüpfungen zwischen beliebigen Objekten';
