-- ============================================
-- Migration: Generic Views, Dynamic Options, Saved Views
-- Date: 2026-03-06
-- ============================================

-- ============================================
-- 1. Add Dynamic Data Source columns to custom_field_definitions
-- ============================================

-- options_source: 'static' (default, current behavior), 'table', 'view'
ALTER TABLE "public"."custom_field_definitions"
    ADD COLUMN IF NOT EXISTS "options_source" text DEFAULT 'static' NOT NULL;

-- The Supabase table or view name to query for dynamic options
ALTER TABLE "public"."custom_field_definitions"
    ADD COLUMN IF NOT EXISTS "source_table" text;

-- Which column in the source table/view provides the option value
ALTER TABLE "public"."custom_field_definitions"
    ADD COLUMN IF NOT EXISTS "source_value_column" text DEFAULT 'id';

-- Which column in the source table/view provides the option label
ALTER TABLE "public"."custom_field_definitions"
    ADD COLUMN IF NOT EXISTS "source_label_column" text DEFAULT 'name';

-- Optional filter criteria for the source query (JSONB)
ALTER TABLE "public"."custom_field_definitions"
    ADD COLUMN IF NOT EXISTS "source_filter" jsonb;

-- Validate options_source values
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'custom_field_definitions_options_source_check'
    ) THEN
        ALTER TABLE "public"."custom_field_definitions"
            ADD CONSTRAINT "custom_field_definitions_options_source_check"
            CHECK (options_source IN ('static', 'table', 'view'));
    END IF;
END $$;


-- ============================================
-- 2. Create saved_views table
-- ============================================

CREATE TABLE IF NOT EXISTS "public"."saved_views" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now() not null,
    "updated_at" timestamp with time zone default now() not null,
    "created_by" bigint references sales(id) on delete cascade,
    "resource" text not null,
    "name" text not null,
    "description" text,
    "filters" jsonb default '{}'::jsonb,
    "sort" jsonb,
    "columns" jsonb,
    "is_default" boolean default false not null,
    "is_shared" boolean default false not null,
    "deleted_at" timestamp with time zone,
    constraint saved_views_pkey primary key (id),
    constraint saved_views_unique_name unique (created_by, resource, name)
);

-- Enable RLS
ALTER TABLE "public"."saved_views" ENABLE ROW LEVEL SECURITY;

-- Policy: Users can see their own views + shared views
DO $$ BEGIN
CREATE POLICY "saved_views_select_policy" ON "public"."saved_views"
    FOR SELECT USING (
        auth.role() = 'authenticated' 
        AND (
            created_by = (SELECT id FROM sales WHERE auth.uid() = user_id LIMIT 1)
            OR is_shared = true
        )
        AND deleted_at IS NULL
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Policy: Users can insert their own views
DO $$ BEGIN
CREATE POLICY "saved_views_insert_policy" ON "public"."saved_views"
    FOR INSERT WITH CHECK (
        auth.role() = 'authenticated'
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Policy: Users can update their own views
DO $$ BEGIN
CREATE POLICY "saved_views_update_policy" ON "public"."saved_views"
    FOR UPDATE USING (
        auth.role() = 'authenticated'
        AND created_by = (SELECT id FROM sales WHERE auth.uid() = user_id LIMIT 1)
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Policy: Users can delete their own views 
DO $$ BEGIN
CREATE POLICY "saved_views_delete_policy" ON "public"."saved_views"
    FOR DELETE USING (
        auth.role() = 'authenticated'
        AND created_by = (SELECT id FROM sales WHERE auth.uid() = user_id LIMIT 1)
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Updated_at trigger helper
CREATE OR REPLACE FUNCTION public.update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Updated_at trigger
CREATE OR REPLACE TRIGGER "saved_views_updated_at"
    BEFORE UPDATE ON "public"."saved_views"
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at();

-- Grant permissions
GRANT ALL ON "public"."saved_views" TO authenticated;
GRANT ALL ON "public"."saved_views" TO anon;
GRANT USAGE, SELECT ON SEQUENCE saved_views_id_seq TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE saved_views_id_seq TO anon;


-- ============================================
-- 3. Helper function: get_table_columns
-- Returns available columns for a given table/view
-- Used by the dynamic options live preview
-- ============================================

CREATE OR REPLACE FUNCTION public.get_table_columns(p_table_name text)
RETURNS TABLE(column_name text, data_type text)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT c.column_name::text, c.data_type::text
    FROM information_schema.columns c
    WHERE c.table_schema = 'public'
      AND c.table_name = p_table_name
    ORDER BY c.ordinal_position;
$$;

-- Grant execute to authenticated users
GRANT EXECUTE ON FUNCTION public.get_table_columns(text) TO authenticated;


-- ============================================
-- 4. Helper function: get_available_tables
-- Returns list of public tables and views for the dynamic source picker
-- ============================================

CREATE OR REPLACE FUNCTION public.get_available_tables()
RETURNS TABLE(table_name text, table_type text)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT t.table_name::text, t.table_type::text
    FROM information_schema.tables t
    WHERE t.table_schema = 'public'
      AND t.table_type IN ('BASE TABLE', 'VIEW')
      AND t.table_name NOT LIKE 'pg_%'
      AND t.table_name NOT LIKE '_realtime%'
      AND t.table_name NOT LIKE 'schema_%'
      AND t.table_name NOT IN ('schema_migrations', 'buckets', 'objects', 's3_multipart_uploads', 's3_multipart_uploads_parts', 'hooks', 'mfa_factors', 'mfa_challenges', 'mfa_amr_claims', 'sso_providers', 'sso_domains', 'saml_providers', 'saml_relay_states', 'flow_state', 'identities', 'instances', 'sessions', 'refresh_tokens', 'audit_log_entries', 'decrypted_secrets', 'secrets')
    ORDER BY t.table_type, t.table_name;
$$;

-- Grant execute to authenticated users
GRANT EXECUTE ON FUNCTION public.get_available_tables() TO authenticated;


-- ============================================
-- 5. Register saved_views in PostgREST schema cache
-- ============================================

NOTIFY pgrst, 'reload schema';
