-- Migration: RBAC System für feingranulare Berechtigungen - VERBESSERT
-- Erstellt Tabellen für Rollen, Berechtigungen und Rollenzuweisungen

-- Tabelle für Rollen
create table if not exists "public"."roles" (
    "id" bigint generated by default as identity not null,
    "name" text not null unique,
    "description" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);

alter table "public"."roles" enable row level security;
CREATE UNIQUE INDEX IF NOT EXISTS roles_pkey ON public.roles USING btree (id);
alter table "public"."roles" add constraint "roles_pkey" PRIMARY KEY using index "roles_pkey";

-- Tabelle für Berechtigungen pro Rolle
create table if not exists "public"."role_permissions" (
    "id" bigint generated by default as identity not null,
    "role_id" bigint not null,
    "resource" text not null,
    "action" text not null,
    "scope" text not null default 'all',
    "created_at" timestamp with time zone not null default now()
);

alter table "public"."role_permissions" enable row level security;
CREATE UNIQUE INDEX IF NOT EXISTS role_permissions_pkey ON public.role_permissions USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS role_permissions_unique ON public.role_permissions USING btree (role_id, resource, action);
alter table "public"."role_permissions" add constraint "role_permissions_pkey" PRIMARY KEY using index "role_permissions_pkey";
alter table "public"."role_permissions" add constraint "role_permissions_role_id_fkey" FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE;

-- Rollenzuweisung zu Benutzern (sales) - nur hinzufügen wenn nicht existiert
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'sales' AND column_name = 'role_id') THEN
    ALTER TABLE "public"."sales" ADD COLUMN "role_id" bigint;
    ALTER TABLE "public"."sales" ADD CONSTRAINT "sales_role_id_fkey" FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE SET NULL;
  END IF;
END $$;

-- Team-Tabelle für Team-basierte Berechtigungen
create table if not exists "public"."teams" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "description" text,
    "created_at" timestamp with time zone not null default now()
);

alter table "public"."teams" enable row level security;
CREATE UNIQUE INDEX IF NOT EXISTS teams_pkey ON public.teams USING btree (id);
alter table "public"."teams" add constraint "teams_pkey" PRIMARY KEY using index "teams_pkey";

-- Team-Mitgliedschaft
create table if not exists "public"."team_members" (
    "id" bigint generated by default as identity not null,
    "team_id" bigint not null,
    "sales_id" bigint not null,
    "is_leader" boolean default false,
    "created_at" timestamp with time zone not null default now()
);

alter table "public"."team_members" enable row level security;
CREATE UNIQUE INDEX IF NOT EXISTS team_members_pkey ON public.team_members USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS team_members_unique ON public.team_members USING btree (team_id, sales_id);
alter table "public"."team_members" add constraint "team_members_pkey" PRIMARY KEY using index "team_members_pkey";
alter table "public"."team_members" add constraint "team_members_team_id_fkey" FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
alter table "public"."team_members" add constraint "team_members_sales_id_fkey" FOREIGN KEY (sales_id) REFERENCES sales(id) ON DELETE CASCADE;

-- =====================================================
-- HILFSFUNKTIONEN
-- =====================================================

-- Aktuellen Sales-Benutzer ermitteln
create or replace function public.get_current_sales_id()
returns bigint
language sql
security definer
stable
as $$
  select id from public.sales where user_id = auth.uid()
$$;

-- Prüfen ob aktueller Benutzer Admin ist (administrator = true ODER keine Rolle zugewiesen bei Admin)
create or replace function public.is_admin()
returns boolean
language sql
security definer
stable
as $$
  select coalesce(
    (select administrator from public.sales where user_id = auth.uid()),
    false
  )
$$;

-- Berechtigung für Ressource und Aktion prüfen - gibt Scope zurück
create or replace function public.check_permission(
  p_resource text,
  p_action text
)
returns text
language sql
security definer
stable
as $$
  select coalesce(
    (
      select rp.scope
      from public.sales s
      join public.role_permissions rp on rp.role_id = s.role_id
      where s.user_id = auth.uid()
        and rp.resource = p_resource
        and rp.action = p_action
    ),
    -- Fallback: Admin bekommt 'all', andere bekommen 'all' wenn keine Rolle definiert
    case 
      when public.is_admin() then 'all'
      else 'all' -- Standard: Alle sehen alles, bis Rolle zugewiesen wird
    end
  )
$$;

-- Team-Mitglieder IDs ermitteln (alle Benutzer im selben Team)
create or replace function public.get_team_member_ids()
returns bigint[]
language sql
security definer
stable
as $$
  select coalesce(
    array_agg(distinct tm2.sales_id),
    ARRAY[public.get_current_sales_id()] -- Mindestens sich selbst
  )
  from public.team_members tm1
  join public.team_members tm2 on tm1.team_id = tm2.team_id
  where tm1.sales_id = public.get_current_sales_id()
$$;

-- KERNFUNKTION: Prüfen ob Benutzer Zugriff auf einen Datensatz hat
create or replace function public.has_record_access(
  p_resource text,
  p_action text,
  p_sales_id bigint
)
returns boolean
language sql
security definer
stable
as $$
  select case public.check_permission(p_resource, p_action)
    when 'all' then true
    when 'own' then (
      p_sales_id IS NULL -- Datensätze ohne Besitzer sind für alle sichtbar
      OR p_sales_id = public.get_current_sales_id()
    )
    when 'team' then (
      p_sales_id IS NULL -- Datensätze ohne Besitzer sind für alle sichtbar
      OR p_sales_id = public.get_current_sales_id()
      OR p_sales_id = any(public.get_team_member_ids())
    )
    when 'none' then false
    else true -- Fallback: Zugriff erlauben
  end
$$;

-- =====================================================
-- STANDARD-ROLLEN UND BERECHTIGUNGEN
-- =====================================================

-- Standard-Rollen erstellen (nur wenn nicht existiert)
INSERT INTO public.roles (name, description) 
VALUES
  ('Administrator', 'Vollzugriff auf alle Ressourcen'),
  ('Vertriebsleiter', 'Zugriff auf Team-Daten und eigene Daten'),
  ('Vertriebsmitarbeiter', 'Nur Zugriff auf eigene Daten')
ON CONFLICT (name) DO NOTHING;

-- Standard-Berechtigungen für Administrator (alle Ressourcen, alle Aktionen, Scope: all)
INSERT INTO public.role_permissions (role_id, resource, action, scope)
SELECT 
  (SELECT id FROM public.roles WHERE name = 'Administrator'),
  resource,
  action,
  'all'
FROM (
  VALUES 
    ('contacts', 'list'), ('contacts', 'show'), ('contacts', 'create'), ('contacts', 'edit'), ('contacts', 'delete'),
    ('companies', 'list'), ('companies', 'show'), ('companies', 'create'), ('companies', 'edit'), ('companies', 'delete'),
    ('deals', 'list'), ('deals', 'show'), ('deals', 'create'), ('deals', 'edit'), ('deals', 'delete'),
    ('tasks', 'list'), ('tasks', 'show'), ('tasks', 'create'), ('tasks', 'edit'), ('tasks', 'delete'),
    ('contact_notes', 'list'), ('contact_notes', 'show'), ('contact_notes', 'create'), ('contact_notes', 'edit'), ('contact_notes', 'delete'),
    ('deal_notes', 'list'), ('deal_notes', 'show'), ('deal_notes', 'create'), ('deal_notes', 'edit'), ('deal_notes', 'delete'),
    ('sales', 'list'), ('sales', 'show'), ('sales', 'create'), ('sales', 'edit'), ('sales', 'delete'),
    ('roles', 'list'), ('roles', 'show'), ('roles', 'create'), ('roles', 'edit'), ('roles', 'delete'),
    ('teams', 'list'), ('teams', 'show'), ('teams', 'create'), ('teams', 'edit'), ('teams', 'delete')
) AS t(resource, action)
ON CONFLICT (role_id, resource, action) DO NOTHING;

-- Standard-Berechtigungen für Vertriebsleiter (Team-Scope)
INSERT INTO public.role_permissions (role_id, resource, action, scope)
SELECT 
  (SELECT id FROM public.roles WHERE name = 'Vertriebsleiter'),
  resource,
  action,
  'team'
FROM (
  VALUES 
    ('contacts', 'list'), ('contacts', 'show'), ('contacts', 'create'), ('contacts', 'edit'), ('contacts', 'delete'),
    ('companies', 'list'), ('companies', 'show'), ('companies', 'create'), ('companies', 'edit'), ('companies', 'delete'),
    ('deals', 'list'), ('deals', 'show'), ('deals', 'create'), ('deals', 'edit'), ('deals', 'delete'),
    ('tasks', 'list'), ('tasks', 'show'), ('tasks', 'create'), ('tasks', 'edit'), ('tasks', 'delete'),
    ('contact_notes', 'list'), ('contact_notes', 'show'), ('contact_notes', 'create'), ('contact_notes', 'edit'), ('contact_notes', 'delete'),
    ('deal_notes', 'list'), ('deal_notes', 'show'), ('deal_notes', 'create'), ('deal_notes', 'edit'), ('deal_notes', 'delete'),
    ('sales', 'list'), ('sales', 'show'),
    ('teams', 'list'), ('teams', 'show')
) AS t(resource, action)
ON CONFLICT (role_id, resource, action) DO NOTHING;

-- Standard-Berechtigungen für Vertriebsmitarbeiter (Own-Scope)
INSERT INTO public.role_permissions (role_id, resource, action, scope)
SELECT 
  (SELECT id FROM public.roles WHERE name = 'Vertriebsmitarbeiter'),
  resource,
  action,
  'own'
FROM (
  VALUES 
    ('contacts', 'list'), ('contacts', 'show'), ('contacts', 'create'), ('contacts', 'edit'),
    ('companies', 'list'), ('companies', 'show'),
    ('deals', 'list'), ('deals', 'show'), ('deals', 'create'), ('deals', 'edit'),
    ('tasks', 'list'), ('tasks', 'show'), ('tasks', 'create'), ('tasks', 'edit'), ('tasks', 'delete'),
    ('contact_notes', 'list'), ('contact_notes', 'show'), ('contact_notes', 'create'), ('contact_notes', 'edit'),
    ('deal_notes', 'list'), ('deal_notes', 'show'), ('deal_notes', 'create'), ('deal_notes', 'edit')
) AS t(resource, action)
ON CONFLICT (role_id, resource, action) DO NOTHING;

-- =====================================================
-- GRANTS
-- =====================================================

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."roles" TO "authenticated";
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."role_permissions" TO "authenticated";
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."teams" TO "authenticated";
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."team_members" TO "authenticated";

GRANT ALL ON TABLE "public"."roles" TO "service_role";
GRANT ALL ON TABLE "public"."role_permissions" TO "service_role";
GRANT ALL ON TABLE "public"."teams" TO "service_role";
GRANT ALL ON TABLE "public"."team_members" TO "service_role";

-- =====================================================
-- RLS POLICIES FÜR RBAC-TABELLEN
-- =====================================================

-- Roles: Lesen für alle, Schreiben nur für Admins
DROP POLICY IF EXISTS "Roles read for authenticated" ON "public"."roles";
CREATE POLICY "Roles read for authenticated" ON "public"."roles"
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Roles write for admins" ON "public"."roles";
CREATE POLICY "Roles write for admins" ON "public"."roles"
  FOR ALL TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

-- Role Permissions: Lesen für alle, Schreiben nur für Admins
DROP POLICY IF EXISTS "Role permissions read for authenticated" ON "public"."role_permissions";
CREATE POLICY "Role permissions read for authenticated" ON "public"."role_permissions"
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Role permissions write for admins" ON "public"."role_permissions";
CREATE POLICY "Role permissions write for admins" ON "public"."role_permissions"
  FOR ALL TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

-- Teams: Lesen für alle, Schreiben nur für Admins
DROP POLICY IF EXISTS "Teams read for authenticated" ON "public"."teams";
CREATE POLICY "Teams read for authenticated" ON "public"."teams"
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Teams write for admins" ON "public"."teams";
CREATE POLICY "Teams write for admins" ON "public"."teams"
  FOR ALL TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

-- Team Members: Lesen für alle, Schreiben nur für Admins
DROP POLICY IF EXISTS "Team members read for authenticated" ON "public"."team_members";
CREATE POLICY "Team members read for authenticated" ON "public"."team_members"
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Team members write for admins" ON "public"."team_members";
CREATE POLICY "Team members write for admins" ON "public"."team_members"
  FOR ALL TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

-- =====================================================
-- RLS POLICIES FÜR CONTACTS MIT RBAC
-- =====================================================

DROP POLICY IF EXISTS "Enable read access for authenticated users" ON "public"."contacts";
DROP POLICY IF EXISTS "Contacts read with RBAC" ON "public"."contacts";
CREATE POLICY "Contacts read with RBAC" ON "public"."contacts"
  FOR SELECT TO authenticated
  USING (
    public.is_admin() 
    OR public.has_record_access('contacts', 'list', sales_id)
  );

DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON "public"."contacts";
DROP POLICY IF EXISTS "Contacts insert with RBAC" ON "public"."contacts";
CREATE POLICY "Contacts insert with RBAC" ON "public"."contacts"
  FOR INSERT TO authenticated
  WITH CHECK (
    public.is_admin()
    OR public.check_permission('contacts', 'create') IN ('all', 'own', 'team')
  );

DROP POLICY IF EXISTS "Enable update for authenticated users only" ON "public"."contacts";
DROP POLICY IF EXISTS "Contacts update with RBAC" ON "public"."contacts";
CREATE POLICY "Contacts update with RBAC" ON "public"."contacts"
  FOR UPDATE TO authenticated
  USING (
    public.is_admin()
    OR public.has_record_access('contacts', 'edit', sales_id)
  )
  WITH CHECK (
    public.is_admin()
    OR public.has_record_access('contacts', 'edit', sales_id)
  );

DROP POLICY IF EXISTS "Contact Delete Policy" ON "public"."contacts";
DROP POLICY IF EXISTS "Contacts delete with RBAC" ON "public"."contacts";
CREATE POLICY "Contacts delete with RBAC" ON "public"."contacts"
  FOR DELETE TO authenticated
  USING (
    public.is_admin()
    OR public.has_record_access('contacts', 'delete', sales_id)
  );

-- =====================================================
-- RLS POLICIES FÜR COMPANIES MIT RBAC
-- =====================================================

DROP POLICY IF EXISTS "Enable read access for authenticated users" ON "public"."companies";
DROP POLICY IF EXISTS "Companies read with RBAC" ON "public"."companies";
CREATE POLICY "Companies read with RBAC" ON "public"."companies"
  FOR SELECT TO authenticated
  USING (
    public.is_admin() 
    OR public.has_record_access('companies', 'list', sales_id)
  );

DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON "public"."companies";
DROP POLICY IF EXISTS "Companies insert with RBAC" ON "public"."companies";
CREATE POLICY "Companies insert with RBAC" ON "public"."companies"
  FOR INSERT TO authenticated
  WITH CHECK (
    public.is_admin()
    OR public.check_permission('companies', 'create') IN ('all', 'own', 'team')
  );

DROP POLICY IF EXISTS "Enable update for authenticated users only" ON "public"."companies";
DROP POLICY IF EXISTS "Companies update with RBAC" ON "public"."companies";
CREATE POLICY "Companies update with RBAC" ON "public"."companies"
  FOR UPDATE TO authenticated
  USING (
    public.is_admin()
    OR public.has_record_access('companies', 'edit', sales_id)
  )
  WITH CHECK (
    public.is_admin()
    OR public.has_record_access('companies', 'edit', sales_id)
  );

DROP POLICY IF EXISTS "Company Delete Policy" ON "public"."companies";
DROP POLICY IF EXISTS "Companies delete with RBAC" ON "public"."companies";
CREATE POLICY "Companies delete with RBAC" ON "public"."companies"
  FOR DELETE TO authenticated
  USING (
    public.is_admin()
    OR public.has_record_access('companies', 'delete', sales_id)
  );

-- =====================================================
-- RLS POLICIES FÜR DEALS MIT RBAC
-- =====================================================

DROP POLICY IF EXISTS "Enable read access for authenticated users" ON "public"."deals";
DROP POLICY IF EXISTS "Deals read with RBAC" ON "public"."deals";
CREATE POLICY "Deals read with RBAC" ON "public"."deals"
  FOR SELECT TO authenticated
  USING (
    public.is_admin() 
    OR public.has_record_access('deals', 'list', sales_id)
  );

DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON "public"."deals";
DROP POLICY IF EXISTS "Deals insert with RBAC" ON "public"."deals";
CREATE POLICY "Deals insert with RBAC" ON "public"."deals"
  FOR INSERT TO authenticated
  WITH CHECK (
    public.is_admin()
    OR public.check_permission('deals', 'create') IN ('all', 'own', 'team')
  );

DROP POLICY IF EXISTS "Enable update for authenticated users only" ON "public"."deals";
DROP POLICY IF EXISTS "Deals update with RBAC" ON "public"."deals";
CREATE POLICY "Deals update with RBAC" ON "public"."deals"
  FOR UPDATE TO authenticated
  USING (
    public.is_admin()
    OR public.has_record_access('deals', 'edit', sales_id)
  )
  WITH CHECK (
    public.is_admin()
    OR public.has_record_access('deals', 'edit', sales_id)
  );

DROP POLICY IF EXISTS "Deals Delete Policy" ON "public"."deals";
DROP POLICY IF EXISTS "Deals delete with RBAC" ON "public"."deals";
CREATE POLICY "Deals delete with RBAC" ON "public"."deals"
  FOR DELETE TO authenticated
  USING (
    public.is_admin()
    OR public.has_record_access('deals', 'delete', sales_id)
  );

-- =====================================================
-- VIEW FÜR BERECHTIGUNGSÜBERSICHT
-- =====================================================

DROP VIEW IF EXISTS "public"."user_permissions";
CREATE VIEW "public"."user_permissions"
WITH (security_invoker=on)
AS
SELECT 
  s.id as sales_id,
  s.first_name,
  s.last_name,
  s.administrator,
  r.name as role_name,
  rp.resource,
  rp.action,
  rp.scope
FROM public.sales s
LEFT JOIN public.roles r ON s.role_id = r.id
LEFT JOIN public.role_permissions rp ON r.id = rp.role_id
WHERE s.user_id = auth.uid();
