-- Migration: EE Modules - Tree, Locks, Events, Search
-- Date: 2026-03-05
-- Supports: ra-tree, ra-realtime (locks), ra-audit-log (events timeline)

-- ============================================
-- 1. TREE: Add parent_id + position to tags (hierarchical tags)
-- ============================================

ALTER TABLE tags ADD COLUMN IF NOT EXISTS parent_id bigint REFERENCES tags(id) ON DELETE SET NULL;
ALTER TABLE tags ADD COLUMN IF NOT EXISTS position integer DEFAULT 0;
CREATE INDEX IF NOT EXISTS idx_tags_parent_id ON tags(parent_id);
CREATE INDEX IF NOT EXISTS idx_tags_position ON tags(position);

-- ============================================
-- 2. TREE: Categories table for hierarchical categorization
-- ============================================

CREATE TABLE IF NOT EXISTS "public"."categories" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "parent_id" bigint references categories(id) on delete set null,
    "position" integer default 0,
    "children" bigint[] default '{}',
    "created_at" timestamp with time zone default now() not null,
    "updated_at" timestamp with time zone default now() not null,
    constraint categories_pkey primary key (id)
);

ALTER TABLE "public"."categories" ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
CREATE POLICY "categories_policy" ON "public"."categories"
    FOR ALL USING (auth.role() = 'authenticated');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS idx_categories_parent_id ON categories(parent_id);

-- ============================================
-- 3. LOCKS: Record locks for ra-realtime
-- ============================================

CREATE TABLE IF NOT EXISTS "public"."locks" (
    "id" bigint generated by default as identity not null,
    "resource" text not null,
    "record_id" text not null,
    "identity" text not null,
    "created_at" timestamp with time zone default now() not null,
    constraint locks_pkey primary key (id),
    constraint locks_unique_resource_record unique (resource, record_id)
);

ALTER TABLE "public"."locks" ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
CREATE POLICY "locks_select" ON "public"."locks"
    FOR SELECT TO authenticated USING (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
CREATE POLICY "locks_insert" ON "public"."locks"
    FOR INSERT TO authenticated WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
CREATE POLICY "locks_delete" ON "public"."locks"
    FOR DELETE TO authenticated USING (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS idx_locks_resource_record ON locks(resource, record_id);

-- ============================================
-- 4. EVENTS: Timeline events table for ra-audit-log
-- (Maps our audit_logs to the "events" resource expected by
--  ra-audit-log Timeline components)
-- ============================================

CREATE OR REPLACE VIEW "public"."events" AS
SELECT
    al.id,
    al.created_at AS "date",
    al.user_id AS "author",
    al.user_name AS "author_name",
    al.resource_type AS "resource",
    al.resource_id AS "recordId",
    al.action,
    jsonb_build_object(
        'old_values', al.old_values,
        'new_values', al.new_values,
        'changed_fields', al.changed_fields,
        'resource_name', al.resource_name,
        'affected_count', al.affected_count
    ) AS "payload"
FROM audit_logs al
ORDER BY al.created_at DESC;

-- ============================================
-- 5. Ensure Supabase Realtime is enabled for key tables
-- ============================================

DO $$
BEGIN
    -- Enable realtime for tables that benefit from live updates
    BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE contacts; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE companies; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE deals; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE tasks; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE contact_notes; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE deal_notes; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE locks; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE audit_logs; EXCEPTION WHEN OTHERS THEN NULL; END;
END $$;

-- ============================================
-- 6. Audit log insert policy for non-admin users  
-- (they need to write their own audit entries)
-- ============================================

-- Already covered by audit_logs_insert policy from previous migration

-- ============================================
-- 7. Allow all authenticated users to read events view
-- ============================================
-- Views inherit from the underlying table policies, so no separate policy needed.
